# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JK Jung's blog
email: jkjung13@gmail.com
description: "My Learning and Sharing about AI and Deep Learning."
baseurl: ""
url: "https://jkjung-avt.github.io"
github_username: jkjung-avt
google_analytics: 'UA-91297312-1'
# twitter_username: 'twitter_username'

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
